### ISSUE TITLE
every time when the page load or page refresh,the handshark method will execute

### ISSUE THREAD

**Issue by zipu888** [cometd/cometd-dojo#6]
every time when the page load or page refresh,the handshark method will execute,cometd server side sessionid change, then the server side sessionID will change,

i remember the cometd server seesion to every web application user in a redis  ,i can push msg to every user that i want to,  but how can i  resolve the frequent handshak

thank u

**Comment by sbordet** [comment]
You can use the [reload extension](http://docs.cometd.org/3/reference/#_extensions_reload).

**Comment by zipu888** [comment]
thank u
